### ISSUE TITLE
Methods are not inherited correctly from super types

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#682]
When a type inherits methods from multiple super types (either classes or interfaces), bcc gets confused in certain situations, leading to either false compile errors or incorrect behaviour (and subsequent crashes).

Example:
The following code results in `Compile Error: Identifier 'b' not found.`, even though it should compile without issues and print "B":
```
SuperStrict
Framework BRL.StandardIO

Interface I
	Method A()
	Method B()
End Interface

Type T1 Implements I Abstract
	Method D() End Method
End Type

Type T2 Extends T1 Abstract
	Method C()
		B
	End Method
End Type

Type T3 Extends T2 Final
	Method A() Override
		Print "A"
	End Method
	Method B() Override
		Print "B"
	End Method
End Type

New T3.C
```

If the `Implements` clause is moved from `T1` to `T2`, the code compiles, but incorrectly calls `A` instead of `B`:
```
SuperStrict
Framework BRL.StandardIO

Interface I
	Method A()
	Method B()
End Interface

Type T1 Abstract
	Method D() End Method
End Type

Type T2 Extends T1 Implements I Abstract
	Method C()
		B
	End Method
End Type

Type T3 Extends T2 Final
	Method A() Override
		Print "A"
	End Method
	Method B() Override
		Print "B"
	End Method
End Type

New T3.C
```
If `A` and `B` have different signatures, this also results in memory corruption.

It does not matter whether `T2` inherits its methods from a class and an interface or from two interfaces: changing `T1` into an interface (and adding `Method D() Override End Method` to `T2` or `T3`) in either of the above samples results in the same issues. *However*, when doing this with the second sample, the bug only occurs if `T2`s super types are kept in the same order: `Type T2 Implements T1, I Abstract` triggers the bug, `Type T2 Implements I, T1 Abstract` on the other hand works correctly.

In every case, adding `Method B() Override Abstract` to `T2`, redeclaring the method that is already inherited from `I` (the compiler recognizes this as an override) functions as a workaround, causing the code to compile and run correctly.

**Comment by GWRon** [comment]
Possibly fixed with: 93f1573a247468f05b7d64d5e748a336209c62df

**Comment by HurryStarfish** [comment]
(Fixed a mistake in the previous post.)
Apparently the `Implements IDerived1` clause on `Type TDerived1` is what makes the difference; without it, the error doesn't occur. It seems that the declaration of `M(TA)` inherited from `IDerived1` somehow interferes with the `M(TB)` in `TDerived1`, even though the two are overloads with different parameters and should be independent from each other for the purposes of overriding.

**Comment by HurryStarfish** [comment]
It seems the original problem, where the wrong method is called, is also not yet fixed in all cases.
I will try to find a code sample to reproduce this.
